name: Check and Test Code

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      session: ${{ steps.set-matrix.outputs.session }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: ./.github/actions/setup-python-env

      - name: Extract nox sessions
        id: set-matrix
        shell: bash
        run: |
          session_list=$(nox --json -l -t check | jq -c '[.[].session]')
          echo "session=$session_list" | tee --append $GITHUB_OUTPUT
  run:
    name: Session ${{ matrix.session }}
    needs: [prepare]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        session: ${{ fromJson(needs.prepare.outputs.session) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - uses: ./.github/actions/setup-python-env
      - name: Run Nox Session ${{ matrix.session }}
        run: nox -s "${{ matrix.session }}"
